name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'thoughts-backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'thoughts-backend/**'
      - '.github/workflows/backend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./thoughts-backend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true
        cache-dependency-path: ./thoughts-backend/go.sum
        
    - name: Install dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v ./...
      
    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o thoughts-backend ./cmd/thoughts-backend
      
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: thoughts-backend
        path: ./thoughts-backend/thoughts-backend
        
  # Uncomment the deploy job when you're ready to set up deployment
  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   
  #   steps:
  #   - name: Download build artifacts
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: thoughts-backend
  #       path: ./thoughts-backend
  #       
  #   - name: Deploy to server
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.SSH_KEY }}
  #       script: |
  #         mkdir -p ~/thoughts-backend
  #         systemctl stop thoughts-backend || true
  #         
  #   - name: Copy binary to server
  #     uses: appleboy/scp-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.SSH_KEY }}
  #       source: "./thoughts-backend"
  #       target: "/home/${{ secrets.USERNAME }}/thoughts-backend/"
  #       
  #   - name: Start service
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.HOST }}
  #       username: ${{ secrets.USERNAME }}
  #       key: ${{ secrets.SSH_KEY }}
  #       script: |
  #         chmod +x ~/thoughts-backend/thoughts-backend
  #         sudo systemctl start thoughts-backend
