name: Build and Test Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'thoughts-backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'thoughts-backend/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./thoughts-backend

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        cache: true
        cache-dependency-path: ./thoughts-backend/go.sum
        
    - name: Install dependencies
      run: go mod download
      
    - name: Run tests
      run: go test -v ./...
      
    - name: Verify build
      run: go build -v ./cmd/thoughts-backend
