name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'thoughts-frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'thoughts-frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./thoughts-frontend
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: ./thoughts-frontend/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint || echo "Linting failed but continuing"
      
    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run build
      
    # Option 1: No artifact storage - just report success
    - name: Display build success
      run: echo "✅ Build completed successfully in $(pwd)/build"
      
  # Alternative direct deployment approach
  deploy:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install dependencies and build
      run: |
        cd ./thoughts-frontend
        npm ci
        npm run build
        
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "./thoughts-frontend/build/*"
        target: "/var/www/html/ishkul.org/"
        strip_components: 2
