name: Terraform Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'deployment/terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'deployment/terraform/**'
  workflow_dispatch:

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check -recursive
      working-directory: ./deployment/terraform
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend=false
      working-directory: ./deployment/terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./deployment/terraform

    - name: Report Format Check
      if: steps.fmt.outcome == 'failure'
      run: |
        echo "::error::Terraform format check failed. Please run 'terraform fmt -recursive' to fix formatting issues."
        exit 1
